version: '3.5'

services:
  db:
    container_name: postgres-db
    image: "postgres:15"
    environment:
      - POSTGRES_USER=
      - POSTGRES_DB=
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  broker:
    container_name: rabbitmq-broker
    image: "rabbitmq:alpine"

  backend:
    build: ./backend
    container_name: backend-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/user/app/

    environment:
      - POSTGRES_USER=
      - POSTGRES_DB=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=amqp://broker:5672//

    depends_on:
      - db
      - broker

  celery:
    build: ./backend
    container_name: celery-runtime
    command: celery --app=backend worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    environment:
      - POSTGRES_USER=
      - POSTGRES_DB=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=amqp://broker:5672//

    depends_on:
      - broker
      - db


volumes:
  postgres_data: