FROM python:3.12-slim

# Install system dependencies
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

WORKDIR /app 


COPY requirements.txt /app


RUN pip install -r requirements.txt 

COPY . /app 

CMD [ "bash","/app/run.sh" ]

EXPOSE 5000